export const PROPERTY_LIST_REQUEST = 'PROPERTY_LIST_REQUEST';
export const PROPERTY_LIST_SUCCESS = 'PROPERTY_LIST_SUCCESS';
export const PROPERTY_LIST_FAILURE = 'PROPERTY_LIST_FAILURE';

export const PROPERTY_DETAILS_REQUEST = 'PROPERTY_DETAILS_REQUEST';
export const PROPERTY_DETAILS_SUCCESS = 'PROPERTY_DETAILS_SUCCESS';
export const PROPERTY_DETAILS_FAILURE = 'PROPERTY_DETAILS_FAILURE';

export const PROPERTY_ADD_REQUEST = 'PROPERTY_ADD_REQUEST';
export const PROPERTY_ADD_SUCCESS = 'PROPERTY_ADD_SUCCESS';
export const PROPERTY_ADD_FAILURE = 'PROPERTY_ADD_FAILURE';
